name: Build and deploy to staging

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the project and build the npm package
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '14.x'
      #     registry-url: 'https://registry.npmjs.org'
      #     scope: "@kuviraio"
      # - name: Install Yarn
      #   run: npm install -g yarn

      # - name: Install dependencies
      #   run: npm install
      # - name: Build
      #   run: npm run build

      - id: Create a npmrc file
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: echo ${{ github.workspace }}
        # run: |
        #   ls ${{ github.workspace }}
        #   cat ${{ github.workspace }}/.npmrc
        #   echo $NPM_CONFIG_USERCONFIG

      # touch ${{ github.workspace }}/.npmrc
      # echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> ${{ github.workspace }}/.npmrc
      # - name: Publish package on NPM 📦
      #   run: npm publish --access public

        # env:
        #   NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        # run: |
        #   npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        #   npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      # - name: Set
      #   env:
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      #   run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
      # - name: Publish the npm package
      #   env:
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      #   run: npm publish --access public
      # env:
      #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
